name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "tag_name=${TAG_NAME}" >> $GITHUB_ENV
          echo "release_name=Release ${TAG_NAME}" >> $GITHUB_ENV
          
          gh release create "${TAG_NAME}" \
            --title "${TAG_NAME}" \
            --notes "Release ${TAG_NAME}" \
            --draft=false \
            --prerelease=false 